name: prepare-docker
description: "Prepares Docker for use in other actions"

inputs:
  registry:
    required: true
    description: "Docker registry"
  username:
    required: true
    description: "Docker username"
  password:
    required: true
    description: "Docker password"

runs:
  using: "composite"
  steps:
    - name: Setup Docker
      uses: docker/login-action@v2
      with:
        registry: trijssenaar.jfrog.io
        username: strijssenaar@xpirit.com
        password: ${{ secrets.DOCKER_APIKEY }}
