name: publish-terraform-module
description: Deploy Terraform module to Terraform Registry

inputs:
  terraformApiKey:
    required: true
    description: "API key for Terraform Registry"

runs:
  using: "composite"
  steps:
    - name: Determine module
      id: module
      run: |
        $name="${{ inputs.terraformModulePath }}".Replace('/','-')
        echo "TERRAFORM_MODULE=$name" >> $env:GITHUB_ENV
        echo "TERRAFORM_PROVIDER=azurerm" >> $env:GITHUB_ENV
      shell: pwsh

    - name: "Artifact: Retrieve"
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: "Deploy: Publish ${{ steps.moduleName.outputs.moduleName }}"
      run: |
        $zipFiles=Get-ChildItem -Path artifacts -Recurse -Filter *.zip
        $zipFiles | ForEach-Object{
          $moduleElements=$_.BaseName.Split('_') 
          $moduleName=$moduleElements[0]
          $moduleProvider=$moduleElements[1]
          $moduleVersion=$moduleElements[2]
          Write-Host "Publishing $moduleName $moduleProvider $moduleVersion..."

          $encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes('${{ inputs.terraformApiKey }}'))
          $Headers = @{
              Authorization = "Basic $encodedCreds"
          }

          Invoke-WebRequest `
            -Headers $Headers `
            -Method Put `
            -Uri "https://trijssenaar.jfrog.io/artifactory/infrastructure-terraform-local/monorepo/$moduleName/$moduleProvider/$moduleVersion.zip" `
            -InFile $_.FullName `
            -ContentType "application/zip"

          # curl `
          #   --user ${{ inputs.terraformApiKey }} `
          #   --request PUT "https://trijssenaar.jfrog.io/artifactory/infrastructure-terraform-local/monorepo/$moduleName/$moduleProvider/$moduleVersion.zip" `
          #   --upload-file $_.FullName
        }
      shell: pwsh
