name: build-prepare
description: "Prepares the build environment for use in other actions"

inputs:
  jfrog-secret-env-1:
    required: true
    description: "JFrog secret environment variable 1"
  docker-apikey:
    required: true
    description: "Docker API key"

runs:
  using: "composite"
  steps:
    - uses: "./.github/template/prepare-gitversion"

    - uses: "./.github/template/prepare-jfrog"
      with:
        secret-env-1: ${{ inputs.jfrog-secret-env-1 }}

    - uses: "./.github/template/prepare-docker"
      with:
        registry: trijssenaar.jfrog.io
        username: strijssenaar@xpirit.com
        password: ${{ inputs.docker-apikey }}
