# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  docker-artifactory:
    type: docker-registry
    url: https://trijssenaar.jfrog.io
    username: ${{ secrets.ARTIFACTORY_USERNAME }}
    password: ${{ secrets.ARTIFACTORY_TOKEN }}
  terraform-artifactory:
    type: terraform-registry
    url: https://trijssenaar.jfrog.io
    token: ${{ secrets.ARTIFACTORY_TOKEN }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/src/app1"
    registries:
      - docker-artifactory
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/src/app2"
    registries:
      - docker-artifactory
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/infra/terraform/deploy/shared-grid"
    registries:
      - terraform-artifactory
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/infra/terraform/modules/keyvault"
    registries:
      - terraform-artifactory
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/infra/terraform/modules/keyvaultcertificates"
    registries:
      - terraform-artifactory
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/infra/terraform/modules/log-analytics"
    registries:
      - terraform-artifactory
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/infra/terraform/modules/monitor-action-group"
    registries:
      - terraform-artifactory
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/infra/terraform/modules/shared-grid"
    registries:
      - terraform-artifactory
    schedule:
      interval: "daily"
