name: prepare-gitversion
description: "Prepares GitVersion for use in other actions"

runs:
  using: "composite"
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: "5.x"

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15

    - run: |
        echo "MONOREPO_FULLSEMVER=${{ steps.gitversion.outputs.FullSemVer }}" >> $env:GITHUB_ENV
        echo "MONOREPO_VERSION=${{ steps.gitversion.outputs.MajorMinorPatch }}.${{ steps.gitversion.outputs.CommitsSinceVersionSource }}" >> $env:GITHUB_ENV
      shell: pwsh
