name: deploy
description: "Deploys an application to an environment"

inputs:
  environment:
    required: true
    description: "Name of the environment to deploy to"

runs:
  using: "composite"
  steps:
    - name: Prepare environment variables
      uses: "./.github/template/prepare-environment-variables"
      with:
        environment: ${{ inputs.environment }}

    - name: Prepare Azure
      uses: "./.github/template/prepare-azure"

    - name: Prepare Terraform state
      uses: "./.github/template/prepare-tfstate"
