name: deploy
description: "Deploys an application to an environment"

inputs:
  environment:
    required: true
    description: "Name of the environment to deploy to"

runs:
  using: "composite"
  steps:
    - uses: ./.github/template/prepare-environment-variables
      with:
        environment: ${{ inputs.environment }}

    - uses: ./.github/template/prepare-azure

    - uses: ./.github/template/prepare-tfstate
      id: prepare-tfstate

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - name: Terraform Build
      run: |
        $ErrorActionPreference = 'Stop'
        terraform version
        terraform -chdir=infra/terraform/deploy/demo/ init -input=false -backend=false
        terraform validate

        Write-Host "resourceGroupName=${{ env.TFSTATE_RESOURCE_GROUP_NAME }}"
        Write-Host "storageAccountName=${{ env.TFSTATE_STORAGE_ACCOUNT_NAME }}"
        Write-Host "containerName=${{ env.TFSTATE_CONTAINER_NAME }}"

      shell: pwsh
