name: deploy
description: "Deploys an application to an environment"

inputs:
  environment:
    required: true
    description: "Name of the environment to deploy to"

runs:
  using: "composite"
  steps:
    - name: Prepare environment variables
      uses: "./.github/template/prepare-environment-variables"
      with:
        environment: ${{ inputs.environment }}

    - name: Prepare Azure
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Create Terraform state storage account
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $ErrorActionPreference = 'Stop'

          function Get-UniqueString ([string]$id, $length=13)
          {
            $hashArray = (new-object System.Security.Cryptography.SHA512Managed).ComputeHash($id.ToCharArray())
            -join ($hashArray[1..$length] | ForEach-Object { [char]($_ % 26 + [byte][char]'a') })
          }

          $rg=az group create --name $env:RESOURCE_GROUP_NAME --location $env:LOCATION | ConvertFrom-Json
          $storageAccountName = "sa$(Get-UniqueString $rg.id)"
          $sa=az storage account create --name $storageAccountName --location $rg.location --resource-group $rg.name --sku Standard_LRS | ConvertFrom-Json
          $sc=az storage container create --name tfstate --account-name $sa.name | ConvertFrom-Json
          $sc | Output-String
        azPSVersion: "latest"
