name: deploy
description: "Deploys an application to an environment"

inputs:
  environment:
    required: true
    description: "Name of the environment to deploy to"

runs:
  using: "composite"
  steps:
    - uses: ./.github/template/prepare-environment-variables
      with:
        environment: ${{ inputs.environment }}

    - uses: ./.github/template/prepare-azure

    - uses: ./.github/template/prepare-tfstate

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Build
      run: |
        $ErrorActionPreference = 'Stop'
        terraform version
        terraform -chdir=.\infra\terraform\deploy\demo\ init -input=false -backend=false
        terraform validate

        # terraform init -chdir=.\infra\terraform\deploy\demo\ -input=false -backend-config="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" -backend-config="storage_account_name=${{ parameters.storageAccountName }}" -backend-config="container_name=${{ parameters.containerName }}" -backend-config="key=${{ parameters.key }}"
        # terraform ${{ parameters.command }} ${{ parameters.commandOptions }}
      shell: pwsh
