name: deploy
description: "Deploys an application to an environment"

inputs:
  environment:
    required: true
    description: "Name of the environment to deploy to"

runs:
  using: "composite"
  steps:
    - name: Prepare Environment Variables
      uses: ./.github/template/prepare-environment-variables
      with:
        environment: ${{ inputs.environment }}

    - name: Prepare Azure
      uses: ./.github/template/prepare-azure

    - name: Prepare Terraform State
      uses: ./.github/template/prepare-tfstate
      id: prepare-tfstate

    - name: Prepare Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - run: |
        # Terraform Build
        terraform version
        terraform -chdir=infra/terraform/deploy/demo/ init -input=false -backend=false
        terraform validate
      shell: pwsh

    - run: |
        # Terraform Plan
        terraform -chdir=infra/terraform/deploy/demo/ init -input=false -backend-config="resource_group_name=${{ steps.prepare-tfstate.outputs.resourceGroupName }}" -backend-config="storage_account_name=${{ steps.prepare-tfstate.outputs.storageAccountName }}" -backend-config="container_name=${{ steps.prepare-tfstate.outputs.containerName }}" -backend-config="key=${{ inputs.environment }}.tfstate"
        terraform -chdir=infra/terraform/deploy/demo/ plan -var-file="$PWD/.github/environments/${{ inputs.environment }}.tfvars" -out="tfplan" -input=false
      env:
        ARM_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
        ARM_USE_OIDC: "true"
      shell: pwsh

    - name: Store Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.environment }}.tfplan"
        path: infra/terraform/deploy/demo/tfplan

    - name: Retrieve Terraform Plan
      uses: actions/download-artifact@v3
      with:
        name: "${{ inputs.environment }}.tfplan"
        path: artifacts/tfplan

    - run: |
        # Terraform Execute
        ls -la artifacts
        terraform -chdir=infra/terraform/deploy/demo/ init -input=false -backend-config="resource_group_name=${{ steps.prepare-tfstate.outputs.resourceGroupName }}" -backend-config="storage_account_name=${{ steps.prepare-tfstate.outputs.storageAccountName }}" -backend-config="container_name=${{ steps.prepare-tfstate.outputs.containerName }}" -backend-config="key=${{ inputs.environment }}.tfstate"
        terraform -chdir=infra/terraform/deploy/demo/ apply -input=false tfplan
      env:
        ARM_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
        ARM_USE_OIDC: "true"
      shell: pwsh
