name: prepare-azure
description: "Prepares Azure for use in other actions"

runs:
  using: "composite"
  steps:
    - name: Prepare Azure
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
