name: deploy-applications-shared-grid
description: "Deploy applications shared grid"

inputs:
  environment:
    required: true
    description: "Name of the environment to deploy to"

runs:
  using: "composite"
  steps:
    - name: Prepare Environment Variables
      uses: ./.github/template/prepare-environment-variables
      with:
        environment: ${{ inputs.environment }}

    - name: Prepare Azure
      uses: ./.github/template/prepare-azure

    - name: "Load secrets"
      id: secrets
      run: |
        $keyvaults=az keyvault list --resource-group $env:RESOURCE_GROUP_NAME | ConvertFrom-Json | Where-Object { $_.name -like 'main-*-kv'}
        if($keyvaults.Count -ne 1){throw 'Number of available keyvaults not equal to 1'}

        $mainKeyvault=$keyvaults[0]
        $secrets=az keyvault secret list --id $mainKeyvault.properties.vaultUri --maxresults 25 | ConvertFrom-Json
        $secrets | ForEach-Object {
          $secretValue=az keyvault secret show --id $_.id | ConvertFrom-Json
          echo "$($_.name)=${secretValue.value}" >> $env:GITHUB_OUTPUT
        }
      env:
        RESOURCE_GROUP_NAME: ${{ env.RESOURCE_GROUP_NAME }}
      shell: pwsh

    - name: "Show secrets"
      run: |
        Write-Host $env:GITHUB_OUTPUT
        Write-Host $env:VM-ADMIN-PASSWORD
      env:
        VM-ADMIN-PASSWORD: ${{ steps.secrets.outputs.VM-ADMIN-PASSWORD }}
      shell: pwsh
