name: build-terraform-module
description: Build Terraform module

inputs:
  terraformPath:
    required: true
    description: "Path to the terraform files"
    default: "infra/terraform"
  terraformModulePath:
    required: true
    description: "Path to the terraform files"
    default: "module/keyvault"

runs:
  using: "composite"
  steps:
    - uses: "./.github/template/prepare-gitversion"

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15

    - name: Determine module name
      id: moduleName
      run: |
        $moduleName="${{ inputs.terraformModulePath }}".Replace('/','-')
        echo "moduleName=$moduleName" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Prepare Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - name: "Terraform: Validate ${{ steps.moduleName.outputs.moduleName }}"
      run: |
        terraform version
        terraform -chdir=${{ inputs.terraformPath }}/${{ inputs.terraformModulePath }}/ init -input=false -backend=false
        terraform validate
      shell: pwsh

    - name: "Artifact: Store ${{ steps.moduleName.outputs.moduleName }}"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.moduleName.outputs.moduleName }}/azurerm/${{ steps.gitversion.outputs.MajorMinorPatch }}.${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
        path: ${{ inputs.terraformPath }}/${{ inputs.terraformModulePath }}/*.tf
