name: build-terraform-module
description: Build Terraform module

inputs:
  terraformPath:
    required: true
    description: "Path to the terraform files"
    default: "infra/terraform"
  terraformModulePath:
    required: true
    description: "Path to the terraform files"
    default: "module/keyvault"

runs:
  using: "composite"
  steps:
    - uses: "./.github/template/prepare-gitversion"
      id: moduleVersion

    - name: Prepare Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - name: Determine module
      id: module
      run: |
        $name="${{ inputs.terraformModulePath }}".Replace('/','-')
        echo "TERRAFORM_MODULE=$name" >> $env:GITHUB_ENV
        echo "TERRAFORM_PROVIDER=azurerm" >> $env:GITHUB_ENV
      shell: pwsh

    - name: "Terraform: Validate ${{ env.TERRAFORM_MODULE }}"
      run: |
        terraform version
        terraform -chdir=${{ inputs.terraformPath }}/${{ inputs.terraformModulePath }}/ init -input=false -backend=false
        terraform validate

        Remove-Item -Path ${{ inputs.terraformPath }}/${{ inputs.terraformModulePath }}/.terraform** -Force -Recurse
        New-Item -Path artifacts
        zip artifacts/${{ env.TERRAFORM_MODULE }}_${{ env.TERRAFORM_PROVIDER }}_${{ env.MONOREPO_VERSION }}.zip -r ${{ inputs.terraformPath }}/${{ inputs.terraformModulePath }}/**
      shell: pwsh

    - name: "Artifact: Store ${{ env.TERRAFORM_MODULE }}"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.TERRAFORM_MODULE }}_${{ env.TERRAFORM_PROVIDER }}_${{ env.MONOREPO_VERSION }}
        path: artifacts/${{ env.TERRAFORM_MODULE }}_${{ env.TERRAFORM_PROVIDER }}_${{ env.MONOREPO_VERSION }}.zip
