name: build-terraform-module
description: Build Terraform module

inputs:
  terraformPath:
    required: true
    description: "Path to the terraform files"
    default: "infra/terraform"
  terraformModulePath:
    required: true
    description: "Path to the terraform files"
    default: "module/keyvault"

runs:
  using: "composite"
  steps:
    - name: Prepare Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - name: Terraform Build
      run: |
        terraform version
        terraform -chdir=${{ inputs.terraformPath }}/${{ inputs.terraformModulePath }}/ init -input=false -backend=false
        terraform validate
      shell: pwsh

    - run: |
        $Env:MODULE_NAME = "${{ inputs.terraformModulePath }}".Replace('/','-')
      shell: pwsh

    - name: Store Terraform
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.MODULE_NAME }}
        path: ${{ inputs.terraformPath }}/${{ inputs.terraformModulePath }}
