name: prepare-tfstate
description: "Prepares Terraform state for use in other actions"

runs:
  using: "composite"
  steps:
    - name: Prepare Terraform state
      id: tfstate
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $ErrorActionPreference = 'Stop'

          function Get-UniqueString ([string]$id, $length=13)
          {
            $hashArray = (new-object System.Security.Cryptography.SHA512Managed).ComputeHash($id.ToCharArray())
            -join ($hashArray[1..$length] | ForEach-Object { [char]($_ % 26 + [byte][char]'a') })
          }

          $containerName='tfstate'

          $rg=az group create --name $env:TFSTATE_RESOURCE_GROUP_NAME --location $env:TFSTATE_LOCATION | ConvertFrom-Json
          $storageAccountName = "sa$(Get-UniqueString $rg.id)"
          $sa=az storage account create --name $storageAccountName --location $rg.location --resource-group $rg.name --sku Standard_LRS | ConvertFrom-Json
          az storage container create --name $containerName --account-name $sa.name --auth-mode login | ConvertFrom-Json

          echo "TFSTATE_RESOURCE_GROUP_NAME=$($rg.name)"
          echo "TFSTATE_RESOURCE_GROUP_NAME=$($rg.name)" >> $env:GITHUB_OUTPUT
          echo "TFSTATE_STORAGE_ACCOUNT_NAME=$($sa.name)"
          echo "TFSTATE_STORAGE_ACCOUNT_NAME=$($sa.name)" >> $env:GITHUB_OUTPUT
          echo "TFSTATE_CONTAINER_NAME=$containerName"
          echo "TFSTATE_CONTAINER_NAME=$containerName" >> $env:GITHUB_OUTPUT
        azPSVersion: "latest"
