name: deploy-terraform-module
description: Deploy Terraform module to Terraform Registry

runs:
  using: "composite"
  steps:
    - name: Prepare Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6
