name: prepare-jfrog
description: "Prepares JFrog for use in other actions"

inputs:
  secret-env-1:
    required: true
    description: "JFrog secret environment variable 1"

runs:
  using: "composite"
  steps:
    - name: Setup JFrog
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: 2.24.2
      env:
        JF_ENV_1: ${{ inputs.jfrog-secret-env-1}}
