name: prepare-jfrog
description: "Prepares JFrog for use in other actions"

runs:
  using: "composite"
  steps:
    - name: Setup JFrog
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: 2.24.2
      env:
        JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
