name: build-terraform
description: "Builds the terraform infrastructure"

inputs:
  terraformToken:
    required: true
    description: "Token to authenticate with terraform"
  terraformPath:
    required: true
    description: "Path to the terraform files"
    default: "infra/terraform"
  terraformModulePath:
    required: true
    description: "Path to the terraform files"
    default: "deploy/shared-grid"

runs:
  using: "composite"
  steps:
    - uses: "./.github/template/prepare-gitversion"
      id: moduleVersion

    - name: Prepare Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7

    - name: Determine deploy
      id: module
      run: |
        $name="${{ inputs.terraformModulePath }}".Replace('/','-')
        echo "TERRAFORM_MODULE=$name" >> $env:GITHUB_ENV
        echo "TERRAFORM_PROVIDER=azurerm" >> $env:GITHUB_ENV
      shell: pwsh

    - name: "Terraform: Validate ${{ env.TERRAFORM_MODULE }}"
      run: |
        # TODO: Remove this when decent secret replacement is available
        $credentials=([PSObject]@{credentials=@{"trijssenaar.jfrog.io"=@{token="${{ inputs.terraformToken }}"}}}) | ConvertTo-Json
        New-Item -Path ~/.terraform.d -ItemType Directory -Force
        Set-Content -Path ~/.terraform.d/credentials.tfrc.json -Value $credentials

        terraform version; if($LastExitCode){throw}
        terraform -chdir=${{ inputs.terraformPath }}/${{ inputs.terraformModulePath }}/ init -input=false -backend=false; if($LastExitCode){throw}
        terraform validate; if($LastExitCode){throw}

        pushd ${{ inputs.terraformPath }}/${{ inputs.terraformModulePath }};ls -la;zip ${{ env.TERRAFORM_MODULE }}_${{ env.TERRAFORM_PROVIDER }}_${{ env.MONOREPO_VERSION }}.zip -r .;ls -la;popd
      shell: pwsh

    - name: "Artifact: Store ${{ env.TERRAFORM_MODULE }}"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.TERRAFORM_MODULE }}_${{ env.TERRAFORM_PROVIDER }}_${{ env.MONOREPO_VERSION }}
        path: ${{ inputs.terraformPath }}/${{ inputs.terraformModulePath }}/${{ env.TERRAFORM_MODULE }}_${{ env.TERRAFORM_PROVIDER }}_${{ env.MONOREPO_VERSION }}.zip
