name: prepare-environment-variables
description: "Prepares environment variables for use in other actions"

inputs:
  environment-name:
    required: true
    description: "Name of the environment to prepare"

runs:
  using: "composite"
  steps:
    - name: Prepare environment
      run: |
        $ErrorActionPreference = 'Stop'

        Get-Content -Path ./.github/workflows/environments/$env:ENVIRONMENT >> $Env:GITHUB_ENV
      shell: pwsh
      env:
        ENVIRONMENT: ${{ inputs.environment-name }}
