name: prepare-environment-variables
description: "Prepares environment variables for use in other actions"

inputs:
  environment-name:
    required: true
    description: "Name of the environment to prepare"

runs:
  using: "composite"
  steps:
    - name: Prepare environment
      run: |
        $ErrorActionPreference = 'Stop'

        Get-Content -Path ./.github/workflows/environments/${{ inputs.environment-name }} >> $Env:GITHUB_ENV
      shell: pwsh
