name: Build app1

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/app1.yml
      - src/app1/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/app1.yml
      - src/app1/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Build app1 image
        id: build
        run: |
          $ErrorActionPreference = "Stop"

          $application="app1"
          $fullSemVer="${{ steps.gitversion.outputs.FullSemVer }}".Replace('+','.')
          echo "APPLICATION_NAME=${application}"
          echo "APPLICATION_NAME=${application}" >> $env:GITHUB_OUTPUT
          echo "APPLICATION_VERSION=${fullSemVer}"
          echo "APPLICATION_VERSION=${fullSemVer}" >> $env:GITHUB_OUTPUT

          $index = Get-Content ./src/${application}/app/index.html
          $index = $index -replace '(<!--Version-->)(.*)(<!--\/Version-->)', "<!--Version-->${fullSemVer}<!--/Version-->"
          $index | Set-Content ./src/${application}/app/index.html

          $hostName='trijssenaar.jfrog.io'
          $folderName='applications-docker-local'
          $imageName="${application}:${fullSemVer}"
          $fullTag=Join-Path -Path $hostName -ChildPath $folderName | Join-Path -ChildPath $imageName

          docker build `
            --tag ${application}:latest `
            --tag $fullTag `
            ./src/${application}
          echo $env:DOCKER_APIKEY | docker login -u strijssenaar@xpirit.com --password-stdin $docker_hostname
          docker push $fullTag
        shell: pwsh
        env:
          DOCKER_APIKEY: ${{ secrets.DOCKER_APIKEY }}

      - uses: actions/upload-artifact@v3
        name: Store GitHub Workflow artifact
        with:
          name: ${{ steps.build.outputs.APPLICATION_NAME }}
          path: ${{ steps.build.outputs.APPLICATION_NAME }}.tar

    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.FullSemVer }}
      informationalVersion: ${{ steps.gitversion.outputs.InformationalVersion }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app1

      - name: Install JFrog
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.24.2
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - name: Store JFrog artifact
        run: |
          $ErrorActionPreference = "Stop"

          $env:JFROG_CLI_BUILD_NAME='app1'
          $env:JFROG_CLI_BUILD_NUMBER='${{needs.build.outputs.FullSemVer}}'

          jf --version
          jf rt upload app1.tar applications/app1-$($env:JFROG_CLI_BUILD_NUMBER).tar
          jf rt build-publish
        shell: pwsh
