name: Build app1

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/app1.yml
      - src/app1/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/app1.yml
      - src/app1/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14

      - name: Build app1
        run: |
          $ErrorActionPreference = "Stop"

          $fullSemVer="${{ steps.gitversion.outputs.FullSemVer }}".Replace('+','.')

          $index = Get-Content ./src/app1/app/index.html
          $index = $index -replace '(<!--Version-->)(.*)(<!--\/Version-->)', "<!--Version-->$fullSemVer<!--/Version-->"
          $index | Set-Content ./src/app1/app/index.html

          docker build --tag app1:latest --tag app1:$fullSemVer --tag app1:${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}.${{ steps.gitversion.outputs.Patch }} --tag app1:${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }} --tag app1:${{ steps.gitversion.outputs.Major }} ./src/app1
        shell: pwsh
