name: Build app1

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/app1.yml
      - src/app1/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/app1.yml
      - src/app1/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14

      - name: Build app1 image
        run: |
          $ErrorActionPreference = "Stop"

          $application="app1"
          $fullSemVer="${{ steps.gitversion.outputs.FullSemVer }}".Replace('+','.')
          echo "APPLICATION_NAME=${application}"
          echo "APPLICATION_NAME=${application}" >> $GITHUB_ENV
          echo "APPLICATION_VERSION=${fullSemVer}"
          echo "APPLICATION_VERSION=${fullSemVer}" >> $GITHUB_ENV

          $index = Get-Content ./src/${application}/app/index.html
          $index = $index -replace '(<!--Version-->)(.*)(<!--\/Version-->)', "<!--Version-->${fullSemVer}<!--/Version-->"
          $index | Set-Content ./src/${application}/app/index.html

          docker build --tag ${application}:latest --tag ${application}:${fullSemVer} --tag ${application}:${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}.${{ steps.gitversion.outputs.Patch }} --tag ${application}:${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }} --tag ${application}:${{ steps.gitversion.outputs.Major }} ./src/${application}
          docker save ${application}:${fullSemVer} -o ${application}-${fullSemVer}.tar
        shell: pwsh

      - uses: actions/upload-artifact@v3
        name: Store app1 artifact
        with:
          name: ${{ env.APPLICATION_NAME }}
          path: ${{ env.APPLICATION_NAME }}-${{ env.APPLICATION_VERSION }}.tar
