name: Build app2

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/app2.yml
      - src/app2/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/app2.yml
      - src/app2/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14

      - name: Build app2
        run: |
          $ErrorActionPreference = "Stop"

          $fullSemVer="${{ steps.gitversion.outputs.FullSemVer }}".Replace('+','.')
          $fullSemVer

          $index = Get-Content ./src/app2/app/index.html
          $index = $index -replace '(<!--Version-->)(.*)(<!--\/Version-->)', "<!--Version-->$fullSemVer<!--/Version-->"
          $index | Set-Content ./src/app2/app/index.html

          docker build --tag app2:latest --tag app2:$fullSemVer --tag app2:${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}.${{ steps.gitversion.outputs.Patch }} --tag app2:${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }} --tag app2:${{ steps.gitversion.outputs.Major }} ./src/app2
        shell: pwsh
