name: Build app2

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/app2.yml
      - .github/template/build-prepare/**
      - .github/template/build-docker/**
      - src/app2/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/app2.yml
      - .github/template/build-prepare/**
      - .github/template/build-docker/**
      - src/app2/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build prepare
        uses: "./.github/template/build-prepare"
        with:
          jfrog-secret-env-1: ${{ secrets.JF_SECRET_ENV_1 }}
          docker-apikey: ${{ secrets.DOCKER_APIKEY }}

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Build image app2-${{ steps.gitversion.outputs.EscapedBranchName }}
        uses: "./.github/template/build-docker"
        with:
          application-name: app2
          image-name: app2-${{ steps.gitversion.outputs.EscapedBranchName }}
          version: ${{ steps.gitversion.outputs.MajorMinorPatch }}.${{ steps.gitversion.outputs.CommitsSinceVersionSource }}

    outputs:
      MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}
      fullSemVer: ${{ steps.gitversion.outputs.FullSemVer }}
      informationalVersion: ${{ steps.gitversion.outputs.InformationalVersion }}
