name: Build app2

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/app2.yml
      - src/app2/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/app2.yml
      - src/app2/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14

      - name: Build app2 image
        id: build
        run: |
          $ErrorActionPreference = "Stop"

          $application="app2"
          $fullSemVer="${{ steps.gitversion.outputs.FullSemVer }}".Replace('+','.')
          echo "APPLICATION_NAME=${application}"
          echo "APPLICATION_NAME=${application}" >> $env:GITHUB_OUTPUT
          echo "APPLICATION_VERSION=${fullSemVer}"
          echo "APPLICATION_VERSION=${fullSemVer}" >> $env:GITHUB_OUTPUT

          $index = Get-Content ./src/${application}/app/index.html
          $index = $index -replace '(<!--Version-->)(.*)(<!--\/Version-->)', "<!--Version-->${fullSemVer}<!--/Version-->"
          $index | Set-Content ./src/${application}/app/index.html

          docker build --tag ${application}:latest --tag ${application}:${fullSemVer} --tag ${application}:${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}.${{ steps.gitversion.outputs.Patch }} --tag ${application}:${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }} --tag ${application}:${{ steps.gitversion.outputs.Major }} ./src/${application}
          Start-Sleep 10 
          docker save --output ./${application}.tar ${application}:${fullSemVer}
        shell: pwsh

      - uses: actions/upload-artifact@v3
        name: Store GitHub Workflow artifact
        with:
          name: ${{ steps.build.outputs.APPLICATION_NAME }}
          path: ${{ steps.build.outputs.APPLICATION_NAME }}.tar

      - name: Install JFrog
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.24.2
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - name: Store JFrog artifact
        run: |
          $ErrorActionPreference = "Stop"

          jf --version
          jf rt ping
          jf rt upload ${{ steps.build.outputs.APPLICATION_NAME }}.tar example-repo-local/
        shell: pwsh

  deployment_DEV:
    name: Deploy DEV
    runs-on: ubuntu-latest
    needs: build
    environment: app2 DEV
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app2

      - name: Display structure of downloaded files
        run: ls -R

  deployment_TST:
    name: Deploy TST
    runs-on: ubuntu-latest
    needs: deployment_DEV
    environment: app2 TST
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app2

      - name: Display structure of downloaded files
        run: ls -R

  deployment_ACC:
    name: Deploy ACC
    runs-on: ubuntu-latest
    needs: deployment_TST
    environment: app2 ACC
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app2

      - name: Display structure of downloaded files
        run: ls -R

  deployment_PRD:
    name: Deploy PRD
    runs-on: ubuntu-latest
    needs: deployment_ACC
    environment: app2 PRD
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app2

      - name: Display structure of downloaded files
        run: ls -R
