name: terraform-deploy-shared-grid-applications

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/terraform-deploy-shared-grid.yml
      - infra/terraform/deploy/shared-grid/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/terraform-deploy-shared-grid.yml
      - infra/terraform/deploy/shared-grid/**

jobs:
  Deploy-DEV-applications:
    if: github.ref == 'refs/heads/main'
    concurrency: DEV
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/deploy-applications-shared-grid"
        with:
          environment: DEV

  Deploy-TST-applications:
    if: github.ref == 'refs/heads/main'
    concurrency: TST
    environment: TST
    runs-on: ubuntu-latest
    needs:
      - Deploy-DEV
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/deploy-applications-shared-grid"
        with:
          environment: TST
