name: deploy-shared-grid

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/terraform-deploy-shared-grid.yml
      - infra/terraform/deploy/shared-grid/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/terraform-deploy-shared-grid.yml
      - infra/terraform/deploy/shared-grid/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/build-terraform"
        with:
          terraformToken: ${{ secrets.ARTIFACTORY_TOKEN }}
          terraformPath: infra/terraform
          terraformModulePath: deploy/shared-grid

  Deploy-DEV-plan:
    if: github.ref == 'refs/heads/main'
    concurrency: DEV
    environment: DEV-plan
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/deploy-terraform"
        with:
          environment: DEV
          terraformModulePath: deploy/shared-grid

  Deploy-DEV:
    if: github.ref == 'refs/heads/main'
    concurrency: DEV
    environment: DEV
    runs-on: ubuntu-latest
    needs:
      - Deploy-DEV-plan
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/deploy-terraform"
        with:
          environment: DEV
          terraformModulePath: deploy/shared-grid
          terraformApply: true

  Deploy-DEV-applications:
    if: github.ref == 'refs/heads/main'
    concurrency: DEV
    environment: DEV
    runs-on: ubuntu-latest
    needs:
      - Deploy-DEV
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/deploy-applications-shared-grid"
        with:
          environment: DEV

  Deploy-TST-plan:
    if: github.ref == 'refs/heads/main'
    concurrency: TST
    environment: TST-plan
    runs-on: ubuntu-latest
    needs:
      - Deploy-DEV-applications
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/deploy-terraform"
        with:
          environment: TST
          terraformModulePath: deploy/shared-grid

  Deploy-TST:
    if: github.ref == 'refs/heads/main'
    concurrency: TST
    environment: TST
    runs-on: ubuntu-latest
    needs:
      - Deploy-TST-plan
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/deploy-terraform"
        with:
          environment: TST
          terraformModulePath: deploy/shared-grid
          terraformApply: true
