name: Build release

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/release.yml
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/release.yml

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Setup Docker
        uses: docker/login-action@v2
        with:
          registry: trijssenaar.jfrog.io
          username: strijssenaar@xpirit.com
          password: ${{ secrets.DOCKER_APIKEY }}

      - name: Pull images
        id: build
        run: |
          $ErrorActionPreference = "Stop"

          docker pull trijssenaar.jfrog.io/applications-docker-local/app1:0.1.0.95
          docker pull trijssenaar.jfrog.io/applications-docker-local/app2:0.1.0.23
          docker image ls
        shell: pwsh

      # - name: Install JFrog
      #   uses: jfrog/setup-jfrog-cli@v3
      #   with:
      #     version: 2.24.2
      #   env:
      #     JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      # - name: Retrieve JFrog artifacts
      #   run: |
      #     $ErrorActionPreference = "Stop"

      #     $env:JFROG_CLI_BUILD_NAME='release'
      #     $env:JFROG_CLI_BUILD_NUMBER='${{ steps.gitversion.outputs.FullSemVer }}'

      #     jf --version
      #     jf rt ping
      #     jf rt download --build=app1/0.1.0+65 applications/* applications/
      #     jf rt download --build=app2/0.1.0+66 applications/* applications/
      #     jf rt build-publish
      #   shell: pwsh

      # - name: Display structure of downloaded files
      #   run: ls -R
