name: terraform-module-hello-world

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev", "release/*"]
    paths:
      - .github/workflows/terraform-module-hello-world.yml
      - infra/terraform/modules/hello-world/**
  pull_request:
    branches: ["main", "dev", "release/*"]
    paths:
      - .github/workflows/terraform-module-hello-world.yml
      - infra/terraform/modules/hello-world/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/build-terraform-module"
        with:
          terraformToken: ${{ secrets.ARTIFACTORY_TOKEN }}
          terraformPath: infra/terraform
          terraformModulePath: modules/hello-world

  Publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/publish-terraform-module"
        with:
          terraformUsername: ${{ secrets.ARTIFACTORY_USERNAME }}
          terraformToken: ${{ secrets.ARTIFACTORY_TOKEN }}
