name: terraform-module-log-analytics

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/terraform-module-log-analytics.yml
      - infra/terraform/modules/log-analytics/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/terraform-module-log-analytics.yml
      - infra/terraform/modules/log-analytics/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/build-terraform-module"
        with:
          terraformPath: infra/terraform
          terraformModulePath: modules/log-analytics

  Publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/deploy-terraform-module"
        with:
          terraformModulePath: modules/log-analytics
