name: terraform-module-keyvault

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/terraform-module-keyvault.yml
      - .github/template/build-terraform-module/**
      - .github/template/publish-terraform-module/**
      - infra/terraform/modules/keyvault/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/terraform-module-keyvault.yml
      - .github/template/build-terraform-module/**
      - .github/template/publish-terraform-module/**
      - infra/terraform/modules/keyvault/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/build-terraform-module"
        with:
          terraformPath: infra/terraform
          terraformModulePath: modules/keyvault

  Publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "./.github/template/publish-terraform-module"
        with:
          terraformApiKey: ${{ secrets.TERRAFORM_APIKEY }}
